newTuple = ('a', 'b', 'c', 'd', 'e')
newTuple1 = tuple('abcde')
print(newTuple[0])
print(newTuple[-1])
print(newTuple[-2])
print(newTuple[1:3])
print(newTuple[:3])
print(newTuple[1:])
print(newTuple[:])
